#!/bin/bash -f
# Vivado (TM) v2016.4 (64-bit)
#
# Filename    : cudo.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jun 14 20:09:04 CEST 2017
# IP Build 1755317 on Mon Jan 23 20:30:07 MST 2017 
#
# usage: cudo.sh [-help]
# usage: cudo.sh [-lib_map_path]
# usage: cudo.sh [-noclean_files]
# usage: cudo.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'cudo.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm xbip_utils_v3_0_7 c_reg_fd_v12_0_3 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_3 xbip_dsp48_addsub_v3_0_3 xbip_addsub_v3_0_3 c_addsub_v12_0_10 xbip_bram18k_v3_0_3 mult_gen_v12_0_12 blk_mem_gen_v8_3_5)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "cudo.sh - Script generated by export_simulation (Vivado v2016.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "/home/pingwin/VIVADO/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/pingwin/VIVADO/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/pingwin/VIVADO/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/cudo/ipshared/e147/xlconstant.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_xlconstant_0_0/sim/cudo_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/SyncBase.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/InputSERDES.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/ChannelBond.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/bb2c/src/dvi2rgb.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_dvi2rgb_0_0/sim/cudo_dvi2rgb_0_0.vhd" \
    "$ref_dir/../../../bd/cudo/ipshared/69dc/src/rgb2vga.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_rgb2vga_0_0/sim/cudo_rgb2vga_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_3 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_10 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summatr_9u_9u/sim/summatr_9u_9u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summatr_10u_10u/sim/summatr_10u_10u.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/binarisation_0/src/binarisation.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/binarisation_0/sim/binarisation_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/sum_11s_11s/sim/sum_11s_11s.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/sum_10s_10s/sim/sum_10s_10s.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_3 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/mul_8u_11s/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/mul_8u_11s/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/mul_8u_11s/sim/mul_8u_11s.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/delay_5_3/src/delay.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/delay_5_3/sim/delay_5_3.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/delay_3_8/sim/delay_3_8.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/cb_row.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/src/rgb2ycbcr.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/rgb2ycbcr_0/sim/rgb2ycbcr_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/divider_32_20_0/src/mult_32_20_lm/sim/mult_32_20_lm.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/divider_32_20_0/src/divider_32_20.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/divider_32_20_0/sim/divider_32_20_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/mul_12s_12s/sim/mul_12s_12s.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/sub_11u_11u/sim/sub_11u_11u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/sum_24u_24u/sim/sum_24u_24u.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_vb_0_0/src/delayLineBRAM/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/delayLineBRAM/sim/delayLineBRAM.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/add_32u_11u/sim/add_32u_11u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/sub_9u_9u/sim/sub_9u_9u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summ_10s_10s/sim/summ_10s_10s.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summ_11s_11s/sim/summ_11s_11s.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summ_8u_8u/sim/summ_8u_8u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summatr_11u_11u/sim/summatr_11u_11u.vhd" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/src/summatr_12u_12u/sim/summatr_12u_12u.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../kolorowy_kwiatek.srcs/sources_1/bd/cudo/ipshared/100a" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/sobell_1.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/sobell_2.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/delayLinieBRAM_WP.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/two_signal_bram_full_delay.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/sobell_bram_delay.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/median_delay_line.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/median_bram_delay.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/full_bram_delay.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/erosion_delay_line.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/dilatation_delay_line.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/combined_sobell.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/core_adder.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/sobell.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/mux.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/median_5_5.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/erosion.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/draw_shape.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/dilatation.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/average.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/center_seeker.v" \
    "$ref_dir/../../../bd/cudo/ipshared/3066/src/vb.v" \
    "$ref_dir/../../../bd/cudo/ip/cudo_vb_0_0/sim/cudo_vb_0_0.v" \
    "$ref_dir/../../../bd/cudo/hdl/cudo.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.cudo xil_defaultlib.glbl -o cudo_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./cudo_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./cudo.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key cudo_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc cudo_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./cudo.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: cudo.sh [-help]\n\
Usage: cudo.sh [-lib_map_path]\n\
Usage: cudo.sh [-reset_run]\n\
Usage: cudo.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
