# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.cache/wt [current_project]
set_property parent.project_path /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/pingwin/Dokumenty/Verilog/binarisation/lut.coe
add_files -quiet /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib /home/pingwin/Dokumenty/Verilog/binarisation/binarisation.srcs/sources_1/new/binarisation.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top binarisation -part xc7k70tfbv676-1


write_checkpoint -force -noxdef binarisation.dcp

catch { report_utilization -file binarisation_utilization_synth.rpt -pb binarisation_utilization_synth.pb }
