# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.cache/wt [current_project]
set_property parent.project_path /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/pingwin/Dokumenty/Verilog/compound-project/ip-repository [current_project]
set_property ip_output_repo /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/multiplexer/multiplexer.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/multiplexer/multiplexer.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/binarisation_0/binarisation_0.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/binarisation_0/binarisation_0.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sum_24u_24u/sum_24u_24u.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sum_24u_24u/sum_24u_24u.dcp]
read_verilog -library xil_defaultlib {
  /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/new/core_adder.v
  /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/new/delay.v
  /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/new/center_seeker.v
  /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/new/draw_shape.v
  /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/new/vb.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top vb -part xc7z010clg400-1


write_checkpoint -force -noxdef vb.dcp

catch { report_utilization -file vb_utilization_synth.rpt -pb vb_utilization_synth.pb }
