# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/lut/lut.srcs/sources_1/ip/lut/lut.xci
# IP: The module: 'lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/lut/lut.srcs/sources_1/ip/lut/lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/lut/lut.srcs/sources_1/ip/lut/lut.xci
# IP: The module: 'lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/lut/lut.srcs/sources_1/ip/lut/lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
