# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider.xci
# IP: The module: 'h_calculation_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h_calculation_divider'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider.xci
# IP: The module: 'h_calculation_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h_calculation_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
