# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u.xci
# IP: The module: 'add_9s_8u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_9s_8u'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u.xci
# IP: The module: 'add_9s_8u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_9s_8u'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
