# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s.xci
# IP: The module: 'mul_12s_12s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_12s_12s'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s.xci
# IP: The module: 'mul_12s_12s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/mul_12s_12s/mul_12s_12s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_12s_12s'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
