# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/draw_shape_0.xci
# IP: The module: 'draw_shape_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/mul_12s_12s/mul_12s_12s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_12s_12s || ORIG_REF_NAME==mul_12s_12s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/sub_11u_11u/sub_11u_11u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_11u_11u || ORIG_REF_NAME==sub_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/add_24u_24u/add_24u_24u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_24u_24u || ORIG_REF_NAME==add_24u_24u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/draw_shape_0.xci
# IP: The module: 'draw_shape_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/mul_12s_12s/mul_12s_12s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_12s_12s || ORIG_REF_NAME==mul_12s_12s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/sub_11u_11u/sub_11u_11u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_11u_11u || ORIG_REF_NAME==sub_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/draw_shape_0/src/add_24u_24u/add_24u_24u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_24u_24u || ORIG_REF_NAME==add_24u_24u}]
