# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.cache/wt [current_project]
set_property parent.project_path /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/pingwin/Dokumenty/Verilog/compound-project/ip-repository [current_project]
set_property ip_output_repo /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/sub_8u_8u_pos/sub_8u_8u_pos.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/sub_8u_8u_pos/sub_8u_8u_pos.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/sub_8u_8u_signed/sub_8u_8u_signed.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/sub_8u_8u_signed/sub_8u_8u_signed.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/h_calculation_divider/h_calculation_divider.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/mul_10s_7u/mul_10s_7u.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/mul_10s_7u/mul_10s_7u.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/ip/add_9s_8u/add_9s_8u.dcp]
read_verilog -library xil_defaultlib {
  /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/new/switcher.v
  /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/new/selector.v
  /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/new/hsv_delay.v
  /home/pingwin/Dokumenty/Verilog/compound-project/HSV/HSV.srcs/sources_1/new/h_calculation.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top h_calculation -part xc7z010clg400-1


write_checkpoint -force -noxdef h_calculation.dcp

catch { report_utilization -file h_calculation_utilization_synth.rpt -pb h_calculation_utilization_synth.pb }
