# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/two_signed/two_signed.xci
# IP: The module: 'two_signed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/two_signed/two_signed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_signed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/two_signed/two_signed.xci
# IP: The module: 'two_signed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/rgb2ycbcr/rgb2ycbcr.srcs/sources_1/ip/two_signed/two_signed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'two_signed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
