# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/ZYBO_Master.xdc

# Block Designs: bd/cudo/cudo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo || ORIG_REF_NAME==cudo}]

# IP: bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo_clk_wiz_0_0 || ORIG_REF_NAME==cudo_clk_wiz_0_0}]

# IP: bd/cudo/ip/cudo_xlconstant_0_0/cudo_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo_xlconstant_0_0 || ORIG_REF_NAME==cudo_xlconstant_0_0}]

# IP: bd/cudo/ip/cudo_dvi2rgb_0_0/cudo_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo_dvi2rgb_0_0 || ORIG_REF_NAME==cudo_dvi2rgb_0_0}]

# IP: bd/cudo/ip/cudo_rgb2vga_0_0/cudo_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo_rgb2vga_0_0 || ORIG_REF_NAME==cudo_rgb2vga_0_0}]

# IP: bd/cudo/ip/cudo_vb_0_0/cudo_vb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cudo_vb_0_0 || ORIG_REF_NAME==cudo_vb_0_0}]

# XDC: bd/cudo/cudo_ooc.xdc
