# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u.xci
# IP: The module: 'sub_11u_11u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_11u_11u'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u.xci
# IP: The module: 'sub_11u_11u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/sub_11u_11u/sub_11u_11u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_11u_11u'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
