# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/add_24u_24u/add_24u_24u.xci
# IP: The module: 'add_24u_24u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/add_24u_24u/add_24u_24u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_24u_24u'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/add_24u_24u/add_24u_24u.xci
# IP: The module: 'add_24u_24u' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/centroid/centroid.srcs/sources_1/ip/add_24u_24u/add_24u_24u_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_24u_24u'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
