# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pingwin/Dokumenty/Verilog/First/First.cache/wt [current_project]
set_property parent.project_path /home/pingwin/Dokumenty/Verilog/First/First.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_output_repo /home/pingwin/Dokumenty/Verilog/First/First.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/pingwin/Dokumenty/Verilog/First/First.srcs/sources_1/new/big_and.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top big_and -part xc7z020clg484-1


write_checkpoint -force -noxdef big_and.dcp

catch { report_utilization -file big_and_utilization_synth.rpt -pb big_and_utilization_synth.pb }
