# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/hdmi_vga_vb_0_0.xci
# IP: The module: 'hdmi_vga_vb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_9u_9u/summatr_9u_9u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_9u_9u || ORIG_REF_NAME==summatr_9u_9u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_10u_10u/summatr_10u_10u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_10u_10u || ORIG_REF_NAME==summatr_10u_10u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/binarisation_0/binarisation_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==binarisation_0 || ORIG_REF_NAME==binarisation_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/sum_11s_11s/sum_11s_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_11s_11s || ORIG_REF_NAME==sum_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/sum_10s_10s/sum_10s_10s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_10s_10s || ORIG_REF_NAME==sum_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/mul_8u_11s/mul_8u_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_8u_11s || ORIG_REF_NAME==mul_8u_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/delay_5_3/delay_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_5_3 || ORIG_REF_NAME==delay_5_3}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/delay_3_8/delay_3_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_3_8 || ORIG_REF_NAME==delay_3_8}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/mul_12s_12s/mul_12s_12s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_12s_12s || ORIG_REF_NAME==mul_12s_12s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sub_11u_11u/sub_11u_11u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_11u_11u || ORIG_REF_NAME==sub_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sum_24u_24u/sum_24u_24u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_24u_24u || ORIG_REF_NAME==sum_24u_24u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/add_32u_11u/add_32u_11u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32u_11u || ORIG_REF_NAME==add_32u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sub_9u_9u/sub_9u_9u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_9u_9u || ORIG_REF_NAME==sub_9u_9u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_10s_10s/summ_10s_10s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_10s_10s || ORIG_REF_NAME==summ_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_11s_11s/summ_11s_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_11s_11s || ORIG_REF_NAME==summ_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_8u_8u/summ_8u_8u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_8u_8u || ORIG_REF_NAME==summ_8u_8u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_11u_11u/summatr_11u_11u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_11u_11u || ORIG_REF_NAME==summatr_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_12u_12u/summatr_12u_12u.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_12u_12u || ORIG_REF_NAME==summatr_12u_12u}]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/hdmi_vga_vb_0_0.xci
# IP: The module: 'hdmi_vga_vb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_9u_9u/summatr_9u_9u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_9u_9u || ORIG_REF_NAME==summatr_9u_9u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_10u_10u/summatr_10u_10u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_10u_10u || ORIG_REF_NAME==summatr_10u_10u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/binarisation_0/binarisation_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==binarisation_0 || ORIG_REF_NAME==binarisation_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/rgb2ycbcr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2ycbcr_0 || ORIG_REF_NAME==rgb2ycbcr_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/sum_11s_11s/sum_11s_11s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_11s_11s || ORIG_REF_NAME==sum_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/sum_10s_10s/sum_10s_10s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_10s_10s || ORIG_REF_NAME==sum_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/mul_8u_11s/mul_8u_11s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_8u_11s || ORIG_REF_NAME==mul_8u_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/delay_5_3/delay_5_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_5_3 || ORIG_REF_NAME==delay_5_3}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/rgb2ycbcr_0/src/delay_3_8/delay_3_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_3_8 || ORIG_REF_NAME==delay_3_8}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/divider_32_20_0/divider_32_20_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/mul_12s_12s/mul_12s_12s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_12s_12s || ORIG_REF_NAME==mul_12s_12s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sub_11u_11u/sub_11u_11u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_11u_11u || ORIG_REF_NAME==sub_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sum_24u_24u/sum_24u_24u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_24u_24u || ORIG_REF_NAME==sum_24u_24u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/add_32u_11u/add_32u_11u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_32u_11u || ORIG_REF_NAME==add_32u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/sub_9u_9u/sub_9u_9u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_9u_9u || ORIG_REF_NAME==sub_9u_9u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_10s_10s/summ_10s_10s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_10s_10s || ORIG_REF_NAME==summ_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_11s_11s/summ_11s_11s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_11s_11s || ORIG_REF_NAME==summ_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summ_8u_8u/summ_8u_8u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summ_8u_8u || ORIG_REF_NAME==summ_8u_8u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_11u_11u/summatr_11u_11u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_11u_11u || ORIG_REF_NAME==summatr_11u_11u}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/summatr_12u_12u/summatr_12u_12u.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==summatr_12u_12u || ORIG_REF_NAME==summatr_12u_12u}]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_vb_0_0_2/src/delayLineBRAM/delayLineBRAM_ooc.xdc
