# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/hdmi_vga_rgb2ycbcr_0_0.xci
# IP: The module: 'hdmi_vga_rgb2ycbcr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/sum_11s_11s/sum_11s_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_11s_11s || ORIG_REF_NAME==sum_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/sum_10s_10s/sum_10s_10s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_10s_10s || ORIG_REF_NAME==sum_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/mul_8u_11s/mul_8u_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_8u_11s || ORIG_REF_NAME==mul_8u_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/delay_5_3/delay_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_5_3 || ORIG_REF_NAME==delay_5_3}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/delay_3_8/delay_3_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_3_8 || ORIG_REF_NAME==delay_3_8}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/hdmi_vga_rgb2ycbcr_0_0.xci
# IP: The module: 'hdmi_vga_rgb2ycbcr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/sum_11s_11s/sum_11s_11s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_11s_11s || ORIG_REF_NAME==sum_11s_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/sum_10s_10s/sum_10s_10s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_10s_10s || ORIG_REF_NAME==sum_10s_10s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/mul_8u_11s/mul_8u_11s.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mul_8u_11s || ORIG_REF_NAME==mul_8u_11s}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/delay_5_3/delay_5_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_5_3 || ORIG_REF_NAME==delay_5_3}]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/tor-wizyjny.srcs/sources_1/bd/hdmi_vga/ip/hdmi_vga_rgb2ycbcr_0_0/src/delay_3_8/delay_3_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delay_3_8 || ORIG_REF_NAME==delay_3_8}]
