# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/summ_10s_10s/summ_10s_10s.xci
# IP: The module: 'summ_10s_10s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/summ_10s_10s/summ_10s_10s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'summ_10s_10s'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/summ_10s_10s/summ_10s_10s.xci
# IP: The module: 'summ_10s_10s' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/vb/vb.srcs/sources_1/ip/summ_10s_10s/summ_10s_10s_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'summ_10s_10s'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
