# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.xci
# IP: The module: 'cudo_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.xci
# IP: The module: 'cudo_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/kolorowy_kwiatek/kolorowy_kwiatek.srcs/sources_1/bd/cudo/ip/cudo_clk_wiz_0_0/cudo_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cudo_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
