# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sum_11s_11s/sum_11s_11s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_11s_11s || ORIG_REF_NAME==sum_11s_11s}]

# IP: ip/sum_10s_10s/sum_10s_10s.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sum_10s_10s || ORIG_REF_NAME==sum_10s_10s}]
