# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.cache/wt [current_project]
set_property parent.project_path /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/pingwin/Dokumenty/Verilog/compound-project/ip-repository [current_project]
set_property ip_output_repo /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/mul_8u_11s/mul_8u_11s.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/mul_8u_11s/mul_8u_11s.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/delay_5_3/delay_5_3.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/delay_5_3/delay_5_3.dcp]
add_files -quiet /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/delay_3_8/delay_3_8.dcp
set_property used_in_implementation false [get_files /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/delay_3_8/delay_3_8.dcp]
read_verilog -library xil_defaultlib {
  /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/new/cb_row.v
  /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/new/rgb2ycbcr.v
}
read_ip -quiet /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_11s_11s/sum_11s_11s.xci
set_property used_in_implementation false [get_files -all /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_11s_11s/sum_11s_11s_ooc.xdc]
set_property is_locked true [get_files /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_11s_11s/sum_11s_11s.xci]

read_ip -quiet /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_10s_10s/sum_10s_10s.xci
set_property used_in_implementation false [get_files -all /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_10s_10s/sum_10s_10s_ooc.xdc]
set_property is_locked true [get_files /home/pingwin/Dokumenty/Verilog/compound-project/YCbCr/rgb2ycbcr.srcs/sources_1/ip/sum_10s_10s/sum_10s_10s.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top rgb2ycbcr -part xc7z010clg400-1


write_checkpoint -force -noxdef rgb2ycbcr.dcp

catch { report_utilization -file rgb2ycbcr_utilization_synth.rpt -pb rgb2ycbcr_utilization_synth.pb }
