# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/pingwin/Dokumenty/Verilog/compound-project/tor-wizyjny/ZYBO_Master.xdc

# Block Designs: bd/hdmi_vga/hdmi_vga.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga || ORIG_REF_NAME==hdmi_vga}]

# IP: bd/hdmi_vga/ip/hdmi_vga_rgb2vga_0_0/hdmi_vga_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_vga_rgb2vga_0_0}]

# IP: bd/hdmi_vga/ip/hdmi_vga_dvi2rgb_0_0/hdmi_vga_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_vga_dvi2rgb_0_0}]

# IP: bd/hdmi_vga/ip/hdmi_vga_clk_wiz_0_0/hdmi_vga_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_vga_clk_wiz_0_0}]

# IP: bd/hdmi_vga/ip/hdmi_vga_xlconstant_0_0/hdmi_vga_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_xlconstant_0_0 || ORIG_REF_NAME==hdmi_vga_xlconstant_0_0}]

# IP: bd/hdmi_vga/ip/hdmi_vga_vb_0_0/hdmi_vga_vb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_vga_vb_0_0 || ORIG_REF_NAME==hdmi_vga_vb_0_0}]

# XDC: bd/hdmi_vga/hdmi_vga_ooc.xdc
